### ISSUE TITLE
Exception Emitted In Logging: Keystore ServiceSpecificException

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-common-for-android#317]
```java
2018-12-06 17:02:15.103 32153-32169/com.microsoft.identity.common.test V/StorageHelper: Starting encryption
2018-12-06 17:02:15.108 32153-32169/com.microsoft.identity.common.test V/StorageHelper: Reading Key entry
2018-12-06 17:02:15.149 32153-32169/com.microsoft.identity.common.test W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.readKeyPair(StorageHelper.java:418)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.getKey(StorageHelper.java:363)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.getKeyOrCreate(StorageHelper.java:325)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.loadSecretKeyForEncryption(StorageHelper.java:304)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.loadSecretKeyForEncryption(StorageHelper.java:291)
        at com.microsoft.identity.common.adal.internal.cache.StorageHelper.encrypt(StorageHelper.java:174)
        at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.encryptDecryptInternal(SharedPreferencesFileManager.java:207)
        at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.encrypt(SharedPreferencesFileManager.java:191)
        at com.microsoft.identity.common.internal.cache.SharedPreferencesFileManager.putString(SharedPreferencesFileManager.java:133)
        at com.microsoft.identity.common.internal.cache.SharedPreferencesAccountCredentialCache.saveAccount(SharedPreferencesAccountCredentialCache.java:93)
        at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.saveAccounts(MsalOAuth2TokenCache.java:658)
        at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:179)
        at com.microsoft.identity.common.MsalOAuth2TokenCacheTest.getAccountsWithDeletion(MsalOAuth2TokenCacheTest.java:651)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
2018-12-06 17:02:15.150 32153-32169/com.microsoft.identity.common.test W/KeyStore:     at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
2018-12-06 17:02:15.154 32153-32169/com.microsoft.identity.common.test V/StorageHelper: Reading SecretKey
2018-12-06 17:02:15.155 32153-32169/com.microsoft.identity.common.test V/StorageHelper: Reading key data from a file
```

**Comment by alfetch** [comment]
Hi.. Is it possible this can be fixed in the 'com.microsoft.identity.client:msal:0.2.2' ?
'com.microsoft.identity.client:msal:0.2.1' has this error.
A fix could be this instead of using getEntry?

https://stackoverflow.com/questions/52024752/android-p-keystore-exception-android-os-servicespecificexception

**Comment by iambmelt** [comment]
@alfetch Are you experiencing specific issues related to this error? Or simply trying to suppress the message?

**Comment by alfetch** [comment]
@iambmelt I need to test it on a android 9 device again. But no it is only a message. Have you understood why this is actually thrown ?

**Comment by iambmelt** [comment]
@alfetch Not really - `developer.android.com`'s sample code for using `KeyStore` continues to [document the use of `getEntry()`](https://developer.android.com/training/articles/keystore#WorkingWithKeyStoreEntries) and the method is not marked `@Deprecated` as of API 28 ([docs](https://developer.android.com/reference/java/security/KeyStore#getEntry(java.lang.String,%20java.security.KeyStore.ProtectionParameter))).

Given that KeyStore [behaves wildly different across Android versions, OEMs, and settings,](https://doridori.github.io/android-security-the-forgetful-keystore/#sthash.A3u2sbtf.dpbs) I'm hesitant to make changes to this logic based _only_ on a log message from the system that doesn't have a clear, documented mitigation. The backstop to all of this is that if users begin to report elevated error rates or issues associated with the current implementation, fixes/updates will be evaluated and applied as necessary.

In working with our partner teams, it's become clear that telemetry around the use of `KeyStore` is necessary: we've observed key-retrieval failures across a variety of devices with greater-than-zero failure rates; something we'd like to better understand.

**Comment by masahiro-ikemoto** [comment]
I referred stackoverflow and modify StorageHelper.readKeyPair() and it works fine on Android9.
See attached diff.
[microsoft-authentication-library-common-for-android-0.0.10.diff.zip](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/files/3312931/microsoft-authentication-library-common-for-android-0.0.10.diff.zip)

**Comment by iambmelt** [comment]
@masahiro-ikemoto If you'd like to see this integrated, can you open a PR so we can review? Cheers

**Comment by masahiro-ikemoto** [comment]
@iambmelt I opened new PR #533 for this problem. Thanks for your suggestion.

**Comment by iambmelt** [comment]
Issue resolved
