### ISSUE TITLE
java.lang.ClassCastException: AccountRecord cannot be cast to MicrosoftStsAccount

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-common-for-android#326]
```java
2018-12-28 13:59:14.316 10030-10820/com.microsoft.identity.client.sample.local E/ApiDispatcher:beginInteractive:  [2018-12-28 21:59:14 - {"thread_id":"5283","correlation_id":"32d17199-a073-4452-8e1e-26bfe8d14769"}] Interactive request failed with Exception Android 24
    java.lang.ClassCastException: com.microsoft.identity.common.internal.dto.AccountRecord cannot be cast to com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsAccount
        at com.microsoft.identity.common.internal.result.MicrosoftStsAuthenticationResult.<init>(MicrosoftStsAuthenticationResult.java:44)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:118)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:64)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by heidijinxujia** [comment]
@kreedula  Could you have a look at this issue? This seems to be caused by [commit ](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/c344d201eccc8edf1df09b63153f59f5d02d4ba9)
