### ISSUE TITLE
Please resolve "Service not registered problem"

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [AzureAD/microsoft-authentication-library-common-for-android#353]
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/454

https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/d4f87ee91b608fd696358e676e2da0d189a2bd2e/common/src/main/java/com/microsoft/identity/common/internal/ui/browser/CustomTabsManager.java#L138

**Comment by MichalDanielDobrzanski** [comment]
```
IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@c4355ab
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3798)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3146)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3191) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2529) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:234) 
        at android.app.ActivityThread.main(ActivityThread.java:5524) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@c4355ab
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1048)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1323)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind(CustomTabsManager.java:138)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose(BrowserAuthorizationStrategy.java:132)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization(BrowserAuthorizationStrategy.java:114)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:235)
        at com.microsoft.identity.client.internal.controllers.MSALInteractiveTokenCommand.notify(MSALInteractiveTokenCommand.java:68)
        at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher.completeInteractive(MSALApiDispatcher.java:244)
        at com.microsoft.identity.client.PublicClientApplication.handleInteractiveRequestRedirect(PublicClientApplication.java:412)
```

**Comment by MichalDanielDobrzanski** [comment]
Looks also that you have a **race condition** problem ->
When someone calls `public synchronized void unbind()` , there is a chance that the boolean `mCustomTabsServiceIsBound` is **still true**, because the **previous instance** of `mCustomTabsServiceConnection` is active and hasn't died yet, even after calling `bind()` shortly after. Everytime you call bind() you create a new instance of `CustomTabsServiceConnection`. 

The most simple fix would be to call `mCustomTabsServiceIsBound = true;` before creating a new `CustomTabsServiceConnection`. Then, in `unbind()` we would always do `unbindService()`.

Please see also: https://stackoverflow.com/questions/22079909/android-java-lang-illegalargumentexception-service-not-registered

**Comment by MichalDanielDobrzanski** [comment]
Looks also that you have a race condition problem ->
When someone calls public synchronized void unbind() , there is a chance that the boolean mCustomTabsServiceIsBound is still true, because the previous instance of mCustomTabsServiceConnection is active and hasn't died yet, even after calling bind() shortly after. Everytime you call bind() you create a new instance of CustomTabsServiceConnection.

The most simple fix would be to call mCustomTabsServiceIsBound = true; before creating a new CustomTabsServiceConnection. Then, in unbind() we would always do unbindService().

Please see also: https://stackoverflow.com/questions/22079909/android-java-lang-illegalargumentexception-service-not-registered

**Comment by MichalDanielDobrzanski** [comment]
The case is can be that you are binding Service to **Activity's** context, not **Application** context and you are creating multiple instances of ServiceConnection on bind(), while previous can live.

I've used Activity context and I was not able to reproduce this error.
```
!CustomTabsClient.bindCustomTabsService(mActivityRef.get().getApplicationContext(), browserPackage, mCustomTabsServiceConnection))
```

And:
```
mActivityRef.get().getApplicationContext().unbindService(mCustomTabsServiceConnection);
```

**Comment by iambmelt** [comment]
@MichalDanielDobrzanski Are you still having this issue with the `1.1.0` release?

**Comment by MichalDanielDobrzanski** [comment]
@iambmelt I am not able to test it since I don't own this device anymore. AFAIK, you have merged my PR with proposed solution. I would try to retest this with "Don't keep activities"
