### ISSUE TITLE
generateSignedJWT failed, audience is missing.

### ISSUE THREAD

**Issue by rpdome** [AzureAD/microsoft-authentication-library-common-for-android#393]
generateSignedJWT throws an exception because "audience" is missing.

However, in getChallengeHeader(final PKeyAuthChallenge pKeyAuthChallenge), we're passing audience with pKeyAuthChallenge.getThumbprint(). and mThumbprint is never set. (In PKeyAuthChallenge constructor, it is always null)

@heidijinxujia FYI

**Comment by kreedula** [comment]
Even I have encountered this 
`java.lang.IllegalArgumentException: audience
        at com.microsoft.identity.common.adal.internal.JWSBuilder.generateSignedJWT(JWSBuilder.java:124)
        at com.microsoft.identity.common.internal.ui.webview.challengehandlers.PKeyAuthChallengeHandler.getChallengeHeader(PKeyAuthChallengeHandler.java:108)
        at com.microsoft.identity.common.internal.ui.webview.challengehandlers.PKeyAuthChallengeHandler.processChallenge(PKeyAuthChallengeHandler.java:66)
        at com.microsoft.identity.common.internal.ui.webview.AzureActiveDirectoryWebViewClient.handleUrl(AzureActiveDirectoryWebViewClient.java:120)
        at com.microsoft.identity.common.internal.ui.webview.AzureActiveDirectoryWebViewClient.shouldOverrideUrlLoading(AzureActiveDirectoryWebViewClient.java:109)
        at aCt.a(SourceFile:1)
        at xH.b(SourceFile:78)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(SourceFile:150)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by kreedula** [comment]
Also since `mThumbprint` is always null, I believe PkeyAuth flow is broken here as the if check here will always be false https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/challengehandlers/PKeyAuthChallengeHandler.java#L101

This needs to be fixed like something we do here in unity : https://github.com/AzureAD/azure-activedirectory-library-for-android-unity-fork/blob/master/adal-unity-fork/src/main/java/com/microsoft/aad/adal/unity/ChallangeResponseBuilder.java#L229

**Comment by kreedula** [comment]
@heidijinxujia FYI, since you're fixing the issue

**Comment by heidijinxujia** [comment]
thank you @kreedula
